CREATE TABLE type(id INTEGER, label INTEGER, singular_label INTEGER, icon INTEGER, top_mentioned_entities TEXT, PRIMARY KEY(id));
INSERT INTO `type` VALUES ('1','7','8','1', '');
INSERT INTO `type` VALUES ('2','9','10','2', '');
CREATE TABLE string(id INTEGER, language TEXT, text TEXT);
INSERT INTO `string` VALUES ('0','de','Alle');
INSERT INTO `string` VALUES ('0','en','All');
INSERT INTO `string` VALUES ('0','en-US','All');
INSERT INTO `string` VALUES ('0','es','Todo');
INSERT INTO `string` VALUES ('0','fr','Toutes');
INSERT INTO `string` VALUES ('0','it','Tutto');
INSERT INTO `string` VALUES ('0','ja','すべて');
INSERT INTO `string` VALUES ('0','nl','Alles');
INSERT INTO `string` VALUES ('0','pt-BR','Todos');
INSERT INTO `string` VALUES ('0','ru','Все');
INSERT INTO `string` VALUES ('0','zh-CN','全部');
INSERT INTO `string` VALUES ('1','de','Buch');
INSERT INTO `string` VALUES ('1','en','Book');
INSERT INTO `string` VALUES ('1','en-US','Book');
INSERT INTO `string` VALUES ('1','es','Libro');
INSERT INTO `string` VALUES ('1','fr','Livre');
INSERT INTO `string` VALUES ('1','it','Libro');
INSERT INTO `string` VALUES ('1','ja','本');
INSERT INTO `string` VALUES ('1','nl','Boeken');
INSERT INTO `string` VALUES ('1','pt-BR','eBook');
INSERT INTO `string` VALUES ('1','ru','Книга');
INSERT INTO `string` VALUES ('1','zh-CN','电子书');
INSERT INTO `string` VALUES ('2','de','Shelfari');
INSERT INTO `string` VALUES ('2','en','Shelfari');
INSERT INTO `string` VALUES ('2','en-US','Shelfari');
INSERT INTO `string` VALUES ('2','es','Shelfari');
INSERT INTO `string` VALUES ('2','fr','Shelfari');
INSERT INTO `string` VALUES ('2','it','Shelfari');
INSERT INTO `string` VALUES ('2','ja','Shelfari');
INSERT INTO `string` VALUES ('2','nl','Shelfari');
INSERT INTO `string` VALUES ('2','pt-BR','Shelfari');
INSERT INTO `string` VALUES ('2','ru','Shelfari');
INSERT INTO `string` VALUES ('2','zh-CN','Shelfari');
INSERT INTO `string` VALUES ('3','de','Kindle-Shop');
INSERT INTO `string` VALUES ('3','en','Kindle Store');
INSERT INTO `string` VALUES ('3','en-US','Kindle Store');
INSERT INTO `string` VALUES ('3','es','Tienda Kindle');
INSERT INTO `string` VALUES ('3','fr','Boutique Kindle');
INSERT INTO `string` VALUES ('3','it','Kindle Store');
INSERT INTO `string` VALUES ('3','ja','Kindleストア');
INSERT INTO `string` VALUES ('3','nl','Kindle-winkel');
INSERT INTO `string` VALUES ('3','pt-BR','Loja Kindle');
INSERT INTO `string` VALUES ('3','ru','Магазин Kindle');
INSERT INTO `string` VALUES ('3','zh-CN','Kindle 商店');
INSERT INTO `string` VALUES ('4','de','Wikipedia');
INSERT INTO `string` VALUES ('4','en','Wikipedia');
INSERT INTO `string` VALUES ('4','en-US','Wikipedia');
INSERT INTO `string` VALUES ('4','es','Wikipedia');
INSERT INTO `string` VALUES ('4','fr','Wikipédia');
INSERT INTO `string` VALUES ('4','it','Wikipedia');
INSERT INTO `string` VALUES ('4','ja','Wikipedia');
INSERT INTO `string` VALUES ('4','nl','Wikipedia');
INSERT INTO `string` VALUES ('4','pt-BR','Wikipédia');
INSERT INTO `string` VALUES ('4','ru','Википедия');
INSERT INTO `string` VALUES ('4','zh-CN','维基百科');
INSERT INTO `string` VALUES ('5','en','Creative Commons Attribution Share-Alike license');
INSERT INTO `string` VALUES ('6','en','http://creativecommons.org/licenses/by-sa/3.0/legalcode');
INSERT INTO `string` VALUES ('1000','de','Wichtige Clips');
INSERT INTO `string` VALUES ('1000','en','Notable Clips');
INSERT INTO `string` VALUES ('1000','en-US','Notable Clips');
INSERT INTO `string` VALUES ('1000','es','Recortes destacables');
INSERT INTO `string` VALUES ('1000','fr','Clips Notable');
INSERT INTO `string` VALUES ('1000','it','Ritagli rilevanti');
INSERT INTO `string` VALUES ('1000','ja','重要な抜粋');
INSERT INTO `string` VALUES ('1000','nl','Opvallende clips');
INSERT INTO `string` VALUES ('1000','pt-BR','Recortes notáveis');
INSERT INTO `string` VALUES ('1000','ru','Важные отрывки');
INSERT INTO `string` VALUES ('1000','zh-CN','选段');
INSERT INTO `string` VALUES ('1001','de','Wichtige Clips');
INSERT INTO `string` VALUES ('1001','en','Notable Clips');
INSERT INTO `string` VALUES ('1001','en-US','Notable Clips');
INSERT INTO `string` VALUES ('1001','es','Recortes destacables');
INSERT INTO `string` VALUES ('1001','fr','Clips Notable');
INSERT INTO `string` VALUES ('1001','it','Ritagli rilevanti');
INSERT INTO `string` VALUES ('1001','ja','重要な抜粋');
INSERT INTO `string` VALUES ('1001','nl','Opvallende clips');
INSERT INTO `string` VALUES ('1001','pt-BR','Recortes notáveis');
INSERT INTO `string` VALUES ('1001','ru','Важные отрывки');
INSERT INTO `string` VALUES ('1001','zh-CN','选段');
INSERT INTO `string` VALUES ('7','de','Personen');
INSERT INTO `string` VALUES ('7','en','People');
INSERT INTO `string` VALUES ('7','en-US','People');
INSERT INTO `string` VALUES ('7','es','Gente');
INSERT INTO `string` VALUES ('7','fr','Personnes');
INSERT INTO `string` VALUES ('7','it','Persone');
INSERT INTO `string` VALUES ('7','ja','人物');
INSERT INTO `string` VALUES ('7','nl','Mensen');
INSERT INTO `string` VALUES ('7','pt-BR','Pessoas');
INSERT INTO `string` VALUES ('7','ru','Люди');
INSERT INTO `string` VALUES ('7','zh-CN','人物');
INSERT INTO `string` VALUES ('8','de','Person');
INSERT INTO `string` VALUES ('8','en','Person');
INSERT INTO `string` VALUES ('8','en-US','Person');
INSERT INTO `string` VALUES ('8','es','Persona');
INSERT INTO `string` VALUES ('8','fr','Personne');
INSERT INTO `string` VALUES ('8','it','Persona');
INSERT INTO `string` VALUES ('8','ja','人物');
INSERT INTO `string` VALUES ('8','nl','Persoon');
INSERT INTO `string` VALUES ('8','pt-BR','Pessoa');
INSERT INTO `string` VALUES ('8','ru','Человек');
INSERT INTO `string` VALUES ('8','zh-CN','人物');
INSERT INTO `string` VALUES ('9','de','Begriffe');
INSERT INTO `string` VALUES ('9','en','Terms');
INSERT INTO `string` VALUES ('9','en-US','Terms');
INSERT INTO `string` VALUES ('9','es','Términos');
INSERT INTO `string` VALUES ('9','fr','Termes');
INSERT INTO `string` VALUES ('9','it','Termini');
INSERT INTO `string` VALUES ('9','ja','トピック');
INSERT INTO `string` VALUES ('9','nl','Termen');
INSERT INTO `string` VALUES ('9','pt-BR','Termos');
INSERT INTO `string` VALUES ('9','ru','Термины');
INSERT INTO `string` VALUES ('9','zh-CN','术语');
INSERT INTO `string` VALUES ('10','de','Begriff');
INSERT INTO `string` VALUES ('10','en','Term');
INSERT INTO `string` VALUES ('10','en-US','Term');
INSERT INTO `string` VALUES ('10','es','Término');
INSERT INTO `string` VALUES ('10','fr','Terme');
INSERT INTO `string` VALUES ('10','it','Termine');
INSERT INTO `string` VALUES ('10','ja','トピック');
INSERT INTO `string` VALUES ('10','nl','Term');
INSERT INTO `string` VALUES ('10','pt-BR','Termo');
INSERT INTO `string` VALUES ('10','ru','Термин');
INSERT INTO `string` VALUES ('10','zh-CN','术语');
INSERT INTO `string` VALUES ('11','de','Themen');
INSERT INTO `string` VALUES ('11','en','Themes');
INSERT INTO `string` VALUES ('11','en-US','Themes');
INSERT INTO `string` VALUES ('11','es','Temas');
INSERT INTO `string` VALUES ('11','fr','Thèmes');
INSERT INTO `string` VALUES ('11','it','Temi');
INSERT INTO `string` VALUES ('11','ja','テーマ');
INSERT INTO `string` VALUES ('11','nl','Thema''s');
INSERT INTO `string` VALUES ('11','pt-BR','Tema');
INSERT INTO `string` VALUES ('11','ru','Темы');
INSERT INTO `string` VALUES ('11','zh-CN','主题');
INSERT INTO `string` VALUES ('12','de','Thema');
INSERT INTO `string` VALUES ('12','en','Theme');
INSERT INTO `string` VALUES ('12','en-US','Theme');
INSERT INTO `string` VALUES ('12','es','Tema');
INSERT INTO `string` VALUES ('12','fr','Thème');
INSERT INTO `string` VALUES ('12','it','Tema');
INSERT INTO `string` VALUES ('12','ja','テーマ');
INSERT INTO `string` VALUES ('12','nl','Thema''s');
INSERT INTO `string` VALUES ('12','pt-BR','Tema');
INSERT INTO `string` VALUES ('12','ru','Тема');
INSERT INTO `string` VALUES ('12','zh-CN','主题');
INSERT INTO `string` VALUES ('13','en','store://%s');
INSERT INTO `string` VALUES ('14','en','http://en.wikipedia.org/wiki/%s');
INSERT INTO `string` VALUES ('15','en','http://www.shelfari.com/books/9707144/A-Tale-of-Two-Cities?amatc=xray');
CREATE TABLE source(id INTEGER, label INTEGER, url INTEGER, license_label INTEGER, license_url INTEGER, PRIMARY KEY(id));
INSERT INTO `source` VALUES ('0','3','13',NULL,NULL);
INSERT INTO `source` VALUES ('1','4','14','5','6');
INSERT INTO `source` VALUES ('2','2','15',NULL,NULL);
CREATE TABLE occurrence(entity INTEGER, start INTEGER, length INTEGER);
CREATE TABLE excerpt(id INTEGER, start INTEGER, length INTEGER, image TEXT, related_entities TEXT, goto INTEGER, PRIMARY KEY(id));
CREATE TABLE entity_excerpt(entity INTEGER, excerpt INTEGER);
CREATE TABLE entity_description(text TEXT, source_wildcard TEXT, source INTEGER, entity INTEGER, PRIMARY KEY(entity));
CREATE TABLE entity(id INTEGER, label TEXT, loc_label INTEGER, type INTEGER, count INTEGER, has_info_card TINYINT, PRIMARY KEY(id));
INSERT INTO `entity` VALUES ('0',NULL,'1',NULL,NULL,'0');
CREATE TABLE book_metadata(srl INTEGER, erl INTEGER, has_images TINYINT, has_excerpts TINYINT, show_spoilers_default TINYINT, num_people INTEGER, num_terms INTEGER, num_images INTEGER, preview_images TEXT);