//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XRayBuilder.Core.Localization.Core {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CoreStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CoreStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XRayBuilder.Core.src.Localization.Core.CoreStrings", typeof(CoreStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consider adding aliases for this term..
        /// </summary>
        internal static string ConsiderAddingAliases {
            get {
                return ResourceManager.GetString("ConsiderAddingAliases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find any paragraphs in this e-book using any known methods..
        /// </summary>
        internal static string CouldNotLocateAnyParagraphs {
            get {
                return ResourceManager.GetString("CouldNotLocateAnyParagraphs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find any paragraphs normally (p elements or divs with class &apos;paragraph&apos;)..
        /// </summary>
        internal static string CouldNotLocateParagraphsNormally {
            get {
                return ResourceManager.GetString("CouldNotLocateParagraphsNormally", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No locations were found for the term &quot;{0}&quot;.
        /// </summary>
        internal static string NoLocationsFoundForTerm {
            get {
                return ResourceManager.GetString("NoLocationsFoundForTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning e-book content….
        /// </summary>
        internal static string ScanningEbookContent {
            get {
                return ResourceManager.GetString("ScanningEbookContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan time: {0}.
        /// </summary>
        internal static string ScanTime {
            get {
                return ResourceManager.GetString("ScanTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching all book contents (all div elements), which may produce odd results..
        /// </summary>
        internal static string SearchingAllDivs {
            get {
                return ResourceManager.GetString("SearchingAllDivs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
